version: "3"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: myusername
      POSTGRES_PASSWORD: mypassword
      TZ: "Asia/Kolkata"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c timezone='Asia/Kolkata'

volumes:
  postgres_data:
  